### ISSUE TITLE
Finalize dense_vector track

### ISSUE THREAD

**Issue by jtibshirani** [elastic/rally-tracks#234]
In #217 we introduced a new track to test the performance of `dense_vector` fields with kNN search. This issue tracks follow-ups from that work:
* Currently we choose arbitrary vectors from the dataset to use as query vectors. Since performance can be sensitive to what query vector is used, it'd be better to average over a small "test set" containing different query vectors.
* Since kNN search uses an approximate algorithm, it's important to measure result accuracy in addition to latency/ throughput. We should look into reporting accuracy, to guard against regressions and ensure we are using realistic algorithm parameters.

**Comment by mayya-sharipova** [comment]
Other follow-ups:
- Increase the number of documents from the current 2M docs to 10M docs 
   - We expect  indexing of 10M docs to take several hours.  If this is not acceptable,  as an alternative for now we can have a separate challenge of indexing 10M docs where we skip force merging to 1 segment which should reduce indexing time
- Track used heap memory

**Comment by mayya-sharipova** [comment]
cc: @jtibshirani @inqueue 

I've run the vector search track with all 10M docs using 8Gb of heap, and the results are below:

Several things to note here:
- 1.32 % of indexing operations failed with Timeout errors 
    - should we increase timeout for bulk operations?
-  Indexing being throttled in logs (e.g. "[INFO ][o.e.i.IndexingMemoryController] [rally-node-0] now throttling indexing for shard [[vectors][1]]: segment writing can't keep up")
    - should we decrease bulk_size from the current `5000`?
- 100% of force-merge failed because of timeout of 7200 secs. But force merge to a single segment was still continuing in the background and successfully finished before we ran queries.
    -  should we increase timeout for merge?
- Indexing took: 2271.3 secs (38 min) + timeout merging took: 7200 secs (2 hrs) +  wait until all merges are done: 4121.8 secs (69 mins). In total for indexing we needed:  **3 hours 47 mins** 
    -  Is this acceptable? 



```txt
|                                                         Metric |                     Task |       Value |   Unit |
|---------------------------------------------------------------:|-------------------------:|------------:|-------:|
|                                                 Min Throughput |             index-append |     2971.92 | docs/s |
|                                                Mean Throughput |             index-append |     9279.91 | docs/s |
|                                              Median Throughput |             index-append |     13378.8 | docs/s |
|                                                 Max Throughput |             index-append |     13759.4 | docs/s |
|                                   50th percentile service time |             index-append |       312.4 |     ms |
|                                   90th percentile service time |             index-append |     354.416 |     ms |
|                                   99th percentile service time |             index-append |       60950 |     ms |
|                                 99.9th percentile service time |             index-append |     60956.6 |     ms |
|                                  100th percentile service time |             index-append |     60958.1 |     ms |
|                                                     error rate |             index-append |        1.32 |      % |
|                                       100th percentile latency |              force-merge | 7.20075e+06 |     ms |
|                                  100th percentile service time |              force-merge | 7.20075e+06 |     ms |
|                                                     error rate |              force-merge |         100 |      % |
|                                                 Min Throughput | wait-until-merges-finish |           0 |  ops/s |
|                                                Mean Throughput | wait-until-merges-finish |           0 |  ops/s |
|                                              Median Throughput | wait-until-merges-finish |           0 |  ops/s |
|                                                 Max Throughput | wait-until-merges-finish |           0 |  ops/s |
|                                       100th percentile latency | wait-until-merges-finish | 4.12184e+06 |     ms |
|                                  100th percentile service time | wait-until-merges-finish | 4.12184e+06 |     ms |
|                                                     error rate | wait-until-merges-finish |           0 |      % |
|                                                 Min Throughput |         knn-search-10-50 |      180.03 |  ops/s |
|                                                Mean Throughput |         knn-search-10-50 |      180.03 |  ops/s |
|                                              Median Throughput |         knn-search-10-50 |      180.03 |  ops/s |
|                                                 Max Throughput |         knn-search-10-50 |      180.03 |  ops/s |
|                                   50th percentile service time |         knn-search-10-50 |     2.03887 |     ms |
|                                   90th percentile service time |         knn-search-10-50 |     2.37617 |     ms |
|                                   99th percentile service time |         knn-search-10-50 |     2.76411 |     ms |
|                                  100th percentile service time |         knn-search-10-50 |     2.83039 |     ms |
|                                                     error rate |         knn-search-10-50 |           0 |      % |
|                                                 Min Throughput |        knn-search-10-100 |      163.21 |  ops/s |
|                                                Mean Throughput |        knn-search-10-100 |      163.21 |  ops/s |
|                                              Median Throughput |        knn-search-10-100 |      163.21 |  ops/s |
|                                                 Max Throughput |        knn-search-10-100 |      163.21 |  ops/s |
|                                   50th percentile service time |        knn-search-10-100 |     1.90515 |     ms |
|                                   90th percentile service time |        knn-search-10-100 |     2.56586 |     ms |
|                                   99th percentile service time |        knn-search-10-100 |     2.95813 |     ms |
|                                  100th percentile service time |        knn-search-10-100 |     3.41884 |     ms |
|                                                     error rate |        knn-search-10-100 |           0 |      % |
|                                                 Min Throughput |      knn-search-100-1000 |       24.49 |  ops/s |
|                                                Mean Throughput |      knn-search-100-1000 |       24.49 |  ops/s |
|                                              Median Throughput |      knn-search-100-1000 |       24.49 |  ops/s |
|                                                 Max Throughput |      knn-search-100-1000 |       24.49 |  ops/s |
|                                   50th percentile service time |      knn-search-100-1000 |     8.54417 |     ms |
|                                   90th percentile service time |      knn-search-100-1000 |      9.5548 |     ms |
|                                   99th percentile service time |      knn-search-100-1000 |     10.7939 |     ms |
|                                  100th percentile service time |      knn-search-100-1000 |     11.2454 |     ms |
|                                                     error rate |      knn-search-100-1000 |           0 |      % |
|                                                 Min Throughput |       script-score-query |        0.89 |  ops/s |
|                                                Mean Throughput |       script-score-query |        0.93 |  ops/s |
|                                              Median Throughput |       script-score-query |        0.93 |  ops/s |
|                                                 Max Throughput |       script-score-query |        0.95 |  ops/s |
|                                   50th percentile service time |       script-score-query |     973.863 |     ms |
|                                   90th percentile service time |       script-score-query |     984.022 |     ms |
|                                   99th percentile service time |       script-score-query |     991.171 |     ms |
|                                  100th percentile service time |       script-score-query |     1037.43 |     ms |
|                                                     error rate |       script-score-query |           0 |      % |
```

---

**Comment by DJRickyB** [comment]
I've been wondering about `knn-search-10-50` and `knn-search-10-100` taking < 3 ms, is that for real, or are we hitting empty results?

**Comment by mayya-sharipova** [comment]
@DJRickyB Thanks for checking.  Yes, that's for real, these queries should be fast.  There are no empty results in knn search if index is not empty, some k nearest documents are always returned.

**Comment by inqueue** [comment]
> I've run the vector search track with all 10M docs using 8Gb of heap, and the results are below:
> 
> Several things to note here:
> 
> * 1.32 % of indexing operations failed with Timeout errors
>   
>   * should we increase timeout for bulk operations?
> * Indexing being throttled in logs (e.g. "[INFO ][o.e.i.IndexingMemoryController] [rally-node-0] now throttling indexing for shard [[vectors][1]]: segment writing can't keep up")
>   
>   * should we decrease bulk_size from the current `5000`?

Decreasing the bulk size should have a positive impact on indexing timeouts and throttling. We might try reducing `bulk_size` from `5000` to `2500` and check the result.

> * 100% of force-merge failed because of timeout of 7200 secs. But force merge to a single segment was still continuing in the background and successfully finished before we ran queries.
>   
>   * should we increase timeout for force-merge?

I see many tracks set `request-timeout: 7200` and it seems to be a limit to prevent a benchmark from hanging (thank you @DJRickyB). You can set `request-timeout` to the approximate expected time for force merge to complete plus some headroom. How about doubling it to `14400`?

> * Indexing took: 2271.3 secs (38 min) + timeout force-merge took: 7200 secs (2 hrs) +  wait until all merges are done: 4121.8 secs (69 mins). In total for indexing we needed:  **3 hours 47 mins**
>   
>   * Is this acceptable?

Would you mind running it again with `bulk-size: 2500` to check the timing for indexing? We shouldn't have any trouble keeping run time <= 5 hours.

**Comment by mayya-sharipova** [comment]
I've run another benchmarking round with `bulk_size`: 2500, and `request-timeout` for force merge: 14400.
But even with this settings there was 0.5% error rate in indexing (timeout errors), as seen below.

Indexing took :2204.2 secs (37 mins) and  force-merge: 9199.928426 secs (2 hrs 33 mins). In total: 3 hours.

I used the default of `bulk_indexing_clients:8`. @inqueue Should I run another race with a less number of bulk indexing clients (e.g. 4 instead of 8) and check if with this setup we can get rid of indexing errors?

---

```txt
|                                                         Metric |                     Task |       Value |   Unit |
|---------------------------------------------------------------:|-------------------------:|------------:|-------:|
|                     Cumulative indexing time of primary shards |                          |     207.536 |    min |
|             Min cumulative indexing time across primary shards |                          |     12.1779 |    min |
|          Median cumulative indexing time across primary shards |                          |     103.768 |    min |
|             Max cumulative indexing time across primary shards |                          |     195.358 |    min |
|            Cumulative indexing throttle time of primary shards |                          |     20.7745 |    min |
|    Min cumulative indexing throttle time across primary shards |                          |           0 |    min |
| Median cumulative indexing throttle time across primary shards |                          |     10.3873 |    min |
|    Max cumulative indexing throttle time across primary shards |                          |     20.7745 |    min |
|                        Cumulative merge time of primary shards |                          |     145.757 |    min |
|                       Cumulative merge count of primary shards |                          |           6 |        |
|                Min cumulative merge time across primary shards |                          |     72.6382 |    min |
|             Median cumulative merge time across primary shards |                          |     72.8783 |    min |
|                Max cumulative merge time across primary shards |                          |     73.1183 |    min |
|               Cumulative merge throttle time of primary shards |                          |           0 |    min |
|       Min cumulative merge throttle time across primary shards |                          |           0 |    min |
|    Median cumulative merge throttle time across primary shards |                          |           0 |    min |
|       Max cumulative merge throttle time across primary shards |                          |           0 |    min |
|                      Cumulative refresh time of primary shards |                          |     56.6347 |    min |
|                     Cumulative refresh count of primary shards |                          |          36 |        |
|              Min cumulative refresh time across primary shards |                          |     25.7311 |    min |
|           Median cumulative refresh time across primary shards |                          |     28.3173 |    min |
|              Max cumulative refresh time across primary shards |                          |     30.9036 |    min |
|                        Cumulative flush time of primary shards |                          |     85.1819 |    min |
|                       Cumulative flush count of primary shards |                          |          27 |        |
|                Min cumulative flush time across primary shards |                          |     42.2493 |    min |
|             Median cumulative flush time across primary shards |                          |     42.5909 |    min |
|                Max cumulative flush time across primary shards |                          |     42.9326 |    min |
|                                        Total Young Gen GC time |                          |      11.747 |      s |
|                                       Total Young Gen GC count |                          |         478 |        |
|                                          Total Old Gen GC time |                          |           0 |      s |
|                                         Total Old Gen GC count |                          |           0 |        |
|                                                     Store size |                          |     6.78665 |     GB |
|                                                  Translog size |                          | 1.02445e-07 |     GB |
|                                         Heap used for segments |                          |           0 |     MB |
|                                       Heap used for doc values |                          |           0 |     MB |
|                                            Heap used for terms |                          |           0 |     MB |
|                                            Heap used for norms |                          |           0 |     MB |
|                                           Heap used for points |                          |           0 |     MB |
|                                    Heap used for stored fields |                          |           0 |     MB |
|                                                  Segment count |                          |           2 |        |
|                                    Total Ingest Pipeline count |                          |           0 |        |
|                                     Total Ingest Pipeline time |                          |           0 |      s |
|                                   Total Ingest Pipeline failed |                          |           0 |        |
|                                                 Min Throughput |             index-append |     3528.45 | docs/s |
|                                                Mean Throughput |             index-append |     8062.75 | docs/s |
|                                              Median Throughput |             index-append |     10845.2 | docs/s |
|                                                 Max Throughput |             index-append |       11250 | docs/s |
|                                   50th percentile service time |             index-append |     205.824 |     ms |
|                                   90th percentile service time |             index-append |     225.728 |     ms |
|                                   99th percentile service time |             index-append |     385.774 |     ms |
|                                 99.9th percentile service time |             index-append |     60977.2 |     ms |
|                                  100th percentile service time |             index-append |     60978.9 |     ms |
|                                                     error rate |             index-append |        0.55 |      % |
|                                                 Min Throughput |              force-merge |           0 |  ops/s |
|                                                Mean Throughput |              force-merge |           0 |  ops/s |
|                                              Median Throughput |              force-merge |           0 |  ops/s |
|                                                 Max Throughput |              force-merge |           0 |  ops/s |
|                                       100th percentile latency |              force-merge | 9.19993e+06 |     ms |
|                                  100th percentile service time |              force-merge | 9.19993e+06 |     ms |
|                                                     error rate |              force-merge |           0 |      % |
|                                                 Min Throughput | wait-until-merges-finish |      131.48 |  ops/s |
|                                                Mean Throughput | wait-until-merges-finish |      131.48 |  ops/s |
|                                              Median Throughput | wait-until-merges-finish |      131.48 |  ops/s |
|                                                 Max Throughput | wait-until-merges-finish |      131.48 |  ops/s |
|                                       100th percentile latency | wait-until-merges-finish |     7.11586 |     ms |
|                                  100th percentile service time | wait-until-merges-finish |     7.11586 |     ms |
|                                                     error rate | wait-until-merges-finish |           0 |      % |
|                                                 Min Throughput |         knn-search-10-50 |      164.48 |  ops/s |
|                                                Mean Throughput |         knn-search-10-50 |      164.48 |  ops/s |
|                                              Median Throughput |         knn-search-10-50 |      164.48 |  ops/s |
|                                                 Max Throughput |         knn-search-10-50 |      164.48 |  ops/s |
|                                   50th percentile service time |         knn-search-10-50 |     2.08576 |     ms |
|                                   90th percentile service time |         knn-search-10-50 |     2.61208 |     ms |
|                                   99th percentile service time |         knn-search-10-50 |     3.43692 |     ms |
|                                  100th percentile service time |         knn-search-10-50 |     3.67672 |     ms |
|                                                     error rate |         knn-search-10-50 |           0 |      % |
|                                                 Min Throughput |        knn-search-10-100 |      152.21 |  ops/s |
|                                                Mean Throughput |        knn-search-10-100 |      152.21 |  ops/s |
|                                              Median Throughput |        knn-search-10-100 |      152.21 |  ops/s |
|                                                 Max Throughput |        knn-search-10-100 |      152.21 |  ops/s |
|                                   50th percentile service time |        knn-search-10-100 |     2.13403 |     ms |
|                                   90th percentile service time |        knn-search-10-100 |     2.70032 |     ms |
|                                   99th percentile service time |        knn-search-10-100 |     3.50122 |     ms |
|                                  100th percentile service time |        knn-search-10-100 |     3.53239 |     ms |
|                                                     error rate |        knn-search-10-100 |           0 |      % |
|                                                 Min Throughput |      knn-search-100-1000 |       23.31 |  ops/s |
|                                                Mean Throughput |      knn-search-100-1000 |       23.31 |  ops/s |
|                                              Median Throughput |      knn-search-100-1000 |       23.31 |  ops/s |
|                                                 Max Throughput |      knn-search-100-1000 |       23.31 |  ops/s |
|                                   50th percentile service time |      knn-search-100-1000 |      7.8278 |     ms |
|                                   90th percentile service time |      knn-search-100-1000 |     8.54076 |     ms |
|                                   99th percentile service time |      knn-search-100-1000 |     10.0954 |     ms |
|                                  100th percentile service time |      knn-search-100-1000 |     11.7699 |     ms |
|                                                     error rate |      knn-search-100-1000 |           0 |      % |
|                                                 Min Throughput |       script-score-query |        0.91 |  ops/s |
|                                                Mean Throughput |       script-score-query |        0.94 |  ops/s |
|                                              Median Throughput |       script-score-query |        0.94 |  ops/s |
|                                                 Max Throughput |       script-score-query |        0.96 |  ops/s |
|                                   50th percentile service time |       script-score-query |     976.416 |     ms |
|                                   90th percentile service time |       script-score-query |     985.663 |     ms |
|                                   99th percentile service time |       script-score-query |     997.587 |     ms |
|                                  100th percentile service time |       script-score-query |     1002.84 |     ms |
|                                                     error rate |       script-score-query |           0 |      % |
```

**Comment by mayya-sharipova** [comment]
@inqueue  Thanks for your feedback. I've made another run with ` --track-params="bulk_indexing_clients:4,ingest_percentage:100"` and `bulk_size: 2500`, but unfortunately there are still indexing errors (1.81%).

Indexing took :1552 secs (26 mins) and force-merge: 8742.67 (2 hrs 26 mins). In total: 2 hours 50 mins.
Errors like this:
```
Traceback (most recent call last):
  File "/Users/mayyasharipova/Library/Python/3.9/lib/python/site-packages/elasticsearch/_async/http_aiohttp.py", line 291, in perform_request
    async with self.session.request(
  File "/Users/mayyasharipova/Library/Python/3.9/lib/python/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/Users/mayyasharipova/Library/Python/3.9/lib/python/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/Users/mayyasharipova/Library/Python/3.9/lib/python/site-packages/aiohttp/client_reqrep.py", line 905, in start
    self._continue = None
  File "/Users/mayyasharipova/Library/Python/3.9/lib/python/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
```

```txt
[2022-03-02T12:48:19,541][INFO ][o.e.i.IndexingMemoryController] [rally-node-0] now throttling indexing for shard [[vectors][1]]: segment writing can't keep up
[2022-03-02T12:49:44,339][INFO ][o.e.i.IndexingMemoryController] [rally-node-0] now throttling indexing for shard [[vectors][0]]: segment writing can't keep up
``` 

```txt
|                                                         Metric |                     Task |       Value |   Unit |
|---------------------------------------------------------------:|-------------------------:|------------:|-------:|
|                     Cumulative indexing time of primary shards |                          |     291.562 |    min |
|             Min cumulative indexing time across primary shards |                          |     24.0041 |    min |
|          Median cumulative indexing time across primary shards |                          |     145.781 |    min |
|             Max cumulative indexing time across primary shards |                          |     267.558 |    min |
|            Cumulative indexing throttle time of primary shards |                          |     19.5048 |    min |
|    Min cumulative indexing throttle time across primary shards |                          |     9.67487 |    min |
| Median cumulative indexing throttle time across primary shards |                          |     9.75241 |    min |
|    Max cumulative indexing throttle time across primary shards |                          |     9.82995 |    min |
|                        Cumulative merge time of primary shards |                          |     144.932 |    min |
|                       Cumulative merge count of primary shards |                          |          10 |        |
|                Min cumulative merge time across primary shards |                          |     69.5895 |    min |
|             Median cumulative merge time across primary shards |                          |     72.4661 |    min |
|                Max cumulative merge time across primary shards |                          |     75.3427 |    min |
|               Cumulative merge throttle time of primary shards |                          |    0.423267 |    min |
|       Min cumulative merge throttle time across primary shards |                          |           0 |    min |
|    Median cumulative merge throttle time across primary shards |                          |    0.211633 |    min |
|       Max cumulative merge throttle time across primary shards |                          |    0.423267 |    min |
|                      Cumulative refresh time of primary shards |                          |     57.4896 |    min |
|                     Cumulative refresh count of primary shards |                          |          30 |        |
|              Min cumulative refresh time across primary shards |                          |      22.884 |    min |
|           Median cumulative refresh time across primary shards |                          |     28.7448 |    min |
|              Max cumulative refresh time across primary shards |                          |     34.6056 |    min |
|                        Cumulative flush time of primary shards |                          |     67.9261 |    min |
|                       Cumulative flush count of primary shards |                          |          13 |        |
|                Min cumulative flush time across primary shards |                          |     29.8537 |    min |
|             Median cumulative flush time across primary shards |                          |      33.963 |    min |
|                Max cumulative flush time across primary shards |                          |     38.0723 |    min |
|                                        Total Young Gen GC time |                          |      12.222 |      s |
|                                       Total Young Gen GC count |                          |         508 |        |
|                                          Total Old Gen GC time |                          |           0 |      s |
|                                         Total Old Gen GC count |                          |           0 |        |
|                                                     Store size |                          |     5.49992 |     GB |
|                                                  Translog size |                          | 1.02445e-07 |     GB |
|                                                  Segment count |                          |           3 |        |
|                                    Total Ingest Pipeline count |                          |           0 |        |
|                                     Total Ingest Pipeline time |                          |           0 |      s |
|                                   Total Ingest Pipeline failed |                          |           0 |        |
|                                                 Min Throughput |             index-append |     5086.59 | docs/s |
|                                                Mean Throughput |             index-append |     12492.1 | docs/s |
|                                              Median Throughput |             index-append |     15483.1 | docs/s |
|                                                 Max Throughput |             index-append |     19721.3 | docs/s |
|                                   50th percentile service time |             index-append |     364.259 |     ms |
|                                   90th percentile service time |             index-append |     554.559 |     ms |
|                                   99th percentile service time |             index-append |     60899.8 |     ms |
|                                 99.9th percentile service time |             index-append |     60911.8 |     ms |
|                                  100th percentile service time |             index-append |       60985 |     ms |
|                                                     error rate |             index-append |        1.81 |      % |
|                                                 Min Throughput |              force-merge |           0 |  ops/s |
|                                                Mean Throughput |              force-merge |           0 |  ops/s |
|                                              Median Throughput |              force-merge |           0 |  ops/s |
|                                                 Max Throughput |              force-merge |           0 |  ops/s |
|                                       100th percentile latency |              force-merge | 8.74267e+06 |     ms |
|                                  100th percentile service time |              force-merge | 8.74267e+06 |     ms |
|                                                     error rate |              force-merge |           0 |      % |
|                                                 Min Throughput | wait-until-merges-finish |      119.72 |  ops/s |
|                                                Mean Throughput | wait-until-merges-finish |      119.72 |  ops/s |
|                                              Median Throughput | wait-until-merges-finish |      119.72 |  ops/s |
|                                                 Max Throughput | wait-until-merges-finish |      119.72 |  ops/s |
|                                       100th percentile latency | wait-until-merges-finish |     7.98557 |     ms |
|                                  100th percentile service time | wait-until-merges-finish |     7.98557 |     ms |
|                                                     error rate | wait-until-merges-finish |           0 |      % |
|                                                 Min Throughput |         knn-search-10-50 |      183.21 |  ops/s |
|                                                Mean Throughput |         knn-search-10-50 |      183.21 |  ops/s |
|                                              Median Throughput |         knn-search-10-50 |      183.21 |  ops/s |
|                                                 Max Throughput |         knn-search-10-50 |      183.21 |  ops/s |
|                                   50th percentile service time |         knn-search-10-50 |      1.9578 |     ms |
|                                   90th percentile service time |         knn-search-10-50 |      2.2554 |     ms |
|                                   99th percentile service time |         knn-search-10-50 |     2.81308 |     ms |
|                                  100th percentile service time |         knn-search-10-50 |      2.9175 |     ms |
|                                                     error rate |         knn-search-10-50 |           0 |      % |
|                                                 Min Throughput |        knn-search-10-100 |      158.69 |  ops/s |
|                                                Mean Throughput |        knn-search-10-100 |      158.69 |  ops/s |
|                                              Median Throughput |        knn-search-10-100 |      158.69 |  ops/s |
|                                                 Max Throughput |        knn-search-10-100 |      158.69 |  ops/s |
|                                   50th percentile service time |        knn-search-10-100 |      2.1849 |     ms |
|                                   90th percentile service time |        knn-search-10-100 |     2.67049 |     ms |
|                                   99th percentile service time |        knn-search-10-100 |     3.64028 |     ms |
|                                  100th percentile service time |        knn-search-10-100 |     4.06352 |     ms |
|                                                     error rate |        knn-search-10-100 |           0 |      % |
|                                                 Min Throughput |      knn-search-100-1000 |       11.39 |  ops/s |
|                                                Mean Throughput |      knn-search-100-1000 |       11.39 |  ops/s |
|                                              Median Throughput |      knn-search-100-1000 |       11.39 |  ops/s |
|                                                 Max Throughput |      knn-search-100-1000 |       11.39 |  ops/s |
|                                   50th percentile service time |      knn-search-100-1000 |     7.71849 |     ms |
|                                   90th percentile service time |      knn-search-100-1000 |     8.58276 |     ms |
|                                   99th percentile service time |      knn-search-100-1000 |     10.3618 |     ms |
|                                  100th percentile service time |      knn-search-100-1000 |     10.5071 |     ms |
|                                                     error rate |      knn-search-100-1000 |           0 |      % |
|                                                 Min Throughput |       script-score-query |         0.9 |  ops/s |
|                                                Mean Throughput |       script-score-query |        0.93 |  ops/s |
|                                              Median Throughput |       script-score-query |        0.93 |  ops/s |
|                                                 Max Throughput |       script-score-query |        0.95 |  ops/s |
|                                   50th percentile service time |       script-score-query |     971.292 |     ms |
|                                   90th percentile service time |       script-score-query |     1000.67 |     ms |
|                                   99th percentile service time |       script-score-query |     1065.59 |     ms |
|                                  100th percentile service time |       script-score-query |     1072.97 |     ms |
|                                                     error rate |       script-score-query |           0 |      % |
```

**Comment by jtibshirani** [comment]
This issue grew in scope, so I renamed it and opened https://github.com/elastic/rally/issues/1549 to track the remaining work. Closing it out.
