### ISSUE TITLE
float division by zero error

### ISSUE THREAD

**Issue by martijnvg** [elastic/rally-tracks#523]
Running the elastic/logging track the following error occurred when running via esbench:

```
2023-11-27 13:52:02,444 ActorAddr-(T|:42939)/PID:4753 esrally.driver.driver ERROR Could not execute schedule
Traceback (most recent call last):

  File "/home/esbench/rally/esrally/driver/driver.py", line 1920, in __call__
    total_ops, total_ops_unit, request_meta_data = await execute_single(runner, self.es, params, self.on_error)
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/esbench/rally/esrally/driver/driver.py", line 2014, in execute_single
    return_value = await runner(es, params)
                   ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/esbench/rally/esrally/driver/runner.py", line 297, in __call__
    return await self.delegate(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/esbench/rally/esrally/driver/runner.py", line 412, in __call__
    return_value = await self.delegate(*args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/esbench/rally/esrally/driver/runner.py", line 345, in __call__
    return await self.delegate(self.client_extractor(args[0]), *args[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/esbench/.rally/benchmarks/tracks/default/elastic/shared/runners/datastream.py", line 158, in compression_stats
    "json_to_index_ratio": ds_index_size / ds_doc_size,
                           ~~~~~~~~~~~~~~^~~~~~~~~~~~~

ZeroDivisionError: float division by zero
```

The used params:

```
{
    "elasticsearch.local.repo.path": "/Users/mvg/dev/code/elasticsearch/master",
    "elasticsearch.heap.size": "8g",
    "track.name": "elastic/logs",
    "track.challenge": "logging-querying",
    "track.revision": "elastic-logs/index_sorting",
    "track.repository.url": "https://github.com/martijnvg/rally-tracks.git",
    "exclude.tasks": "compression-stats",
    "track.params": {
        "bulk_start_date": "2020-01-01",
        "bulk_end_date": "2020-01-02",
        "bulk_indexing_clients": 24,
        "data_generation_clients": 16,
        "raw_data_volume_per_day": "100GB",
        "max_generated_corpus_size": "40GB",
        "max_total_download_gb": 40,
        "number_of_replicas": 0,
        "number_of_shards": 3,
        "wait_for_status": "green",
        "query_average_interval": "12h",
        "query_max_date": "2020-01-02",
        "query_min_date": "2020-01-01",
        "query_warmup_time_period": 300,
        "query_time_period": 3600,
        "workflow_time_interval": 60,
        "think_time_interval": 10,
        "synthetic_source_mode": true
    },
    "cloud.region": "europe-west4",
    "client.options": {
        "default": {
            "timeout": null
        }
    },
    "kibana.node.count": 1,
    "elasticsearch.node.count": 3
}
```

**Comment by inqueue** [comment]
Closed by https://github.com/elastic/rally-tracks/pull/527
